# Generated by Django 4.2.3 on 2023-07-21 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdExpence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2023, 7, 22, 0, 18, 42, 222906))),
                ('Amount', models.IntegerField(default=2000)),
            ],
            options={
                'db_table': 'Ad Expence',
            },
        ),
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase', models.CharField(max_length=100)),
                ('Remark', models.CharField(max_length=250)),
                ('Amount', models.CharField(max_length=10)),
                ('Date', models.DateField(default=datetime.datetime(2023, 7, 22, 0, 18, 42, 221760))),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sellingPrice', models.IntegerField()),
                ('purchacePrice', models.IntegerField()),
                ('vendor', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('profile_picture', models.FileField(upload_to='profile_picture')),
                ('attachment', models.FileField(upload_to='attachments')),
                ('status', models.BooleanField(default=True)),
                ('access', models.BooleanField(default=True)),
                ('shift', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2023, 7, 22, 0, 18, 42, 223419))),
                ('NumberOfSales', models.IntegerField(blank=True, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('Discount', models.IntegerField(blank=True, default=0)),
                ('Profit', models.IntegerField(blank=True, null=True)),
                ('AdAmount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.adexpence')),
                ('Product', models.ForeignKey(on_delete=models.SET('Deleted'), to='user_app.products')),
                ('Staff', models.ForeignKey(on_delete=models.SET('Deleted'), to='user_app.staffs')),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2023, 7, 22, 0, 18, 42, 221760))),
                ('Description', models.TextField()),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.staffs')),
            ],
            options={
                'db_table': 'Returns',
            },
        ),
    ]
