# Generated by Django 4.2.2 on 2023-07-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purchase', models.CharField(max_length=100)),
                ('Remark', models.CharField(max_length=250)),
                ('Amount', models.CharField(max_length=10)),
                ('Date', models.DateField()),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('profile_picture', models.FileField(upload_to='profile_picture')),
                ('attachment', models.FileField(upload_to='attachments')),
                ('status', models.BooleanField(default=True)),
                ('access', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Description', models.TextField()),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.staffs')),
            ],
            options={
                'db_table': 'Returns',
            },
        ),
    ]
