# Generated by Django 4.2.2 on 2023-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expences',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
