# Generated by Django 4.2.2 on 2023-07-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_expences_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(max_length=500)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.staffs')),
            ],
            options={
                'db_table': 'Return',
            },
        ),
    ]
