# Generated by Django 4.2.2 on 2023-07-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_return'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
