# Generated by Django 4.2.2 on 2023-07-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_delete_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='shift',
            field=models.CharField(default='day', max_length=20),
            preserve_default=False,
        ),
    ]
