# Generated by Django 4.2.3 on 2023-07-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_staffs_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sellingPrice', models.IntegerField()),
                ('purchacePrice', models.IntegerField()),
                ('vendor', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
