# Generated by Django 4.2.3 on 2023-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('NumberOfSales', models.IntegerField(blank=True, null=True)),
                ('Product', models.ForeignKey(on_delete=models.SET('Deleted'), to='user_app.products')),
                ('Staff', models.ForeignKey(on_delete=models.SET('Deleted'), to='user_app.staffs')),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
    ]
